### ISSUE TITLE
Type appears twice in print message

### ISSUE THREAD

**Issue by gowerc** [insightsengineering/rbmi#266]
The word `type` appears twice in the draws print message for condmean. Would be good to clear this / make each element distinct:

```
Method:
    Type: Conditional Mean
    covariance: us
    threshold: 0.01
    same_cov: TRUE
    REML: TRUE
    n_samples: 50
    type: bootstrap
```
